frr version 9.1
frr defaults traditional
hostname spine1
log stdout
!
interface lo
 ip address 10.0.0.100/32
!
interface eth1
 ip address 10.1.1.0/31
 ip ospf network point-to-point
!
interface eth2
 ip address 10.1.2.0/31
 ip ospf network point-to-point
!
interface eth3
 ip address 10.1.3.0/31
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.0.0.100
 network 10.0.0.100/32 area 0
 network 10.1.1.0/31 area 0
 network 10.1.2.0/31 area 0
 network 10.1.3.0/31 area 0
!
router bgp 65000
 bgp router-id 10.0.0.100
 no bgp default ipv4-unicast
 neighbor EVPN-LEAF peer-group
 neighbor EVPN-LEAF remote-as 65000
 neighbor EVPN-LEAF update-source lo
 neighbor 10.0.0.1 peer-group EVPN-LEAF
 neighbor 10.0.0.2 peer-group EVPN-LEAF
 neighbor 10.0.0.3 peer-group EVPN-LEAF
 !
 address-family l2vpn evpn
  neighbor EVPN-LEAF activate
  neighbor EVPN-LEAF route-reflector-client
 exit-address-family
!
line vty
!
